num_classes: &num_classes 2
num_ids: &num_ids 3072
clip_box: &clip_box False
runtime:
  aligned: True
  async_norm: True
  special_bn_init: True
  runner:
    type: motfp16
    kwargs:
      cache: True
  model_helper:
    type: mot
  fp16: True

tracker:
  type: fairtracker
  kwargs:
    cfg: {}
  # type: bytetracker
  # kwargs:
  #   cfg:
  #     track_thresh: 0.6
  #     track_buffer: 30
  #     match_thresh: 0.9
  #     conf_thresh: 0.1

window: &window
  type: window
  kwargs: {}

mosaic: &mosaic
  type: mosaic
  kwargs:
    extra_input: True
    tar_size: &tar_size [800, 1440]
    fill_color: 0
    mosaic_self: False
    clip_box: *clip_box

random_perspective: &random_perspective
  type: random_perspective_yolox
  kwargs:
    degrees: 10.0 # 0.0
    translate: 0.1
    scale: [0.1, 2.0] # 0.5
    shear: 2.0 # 0.0
    perspective: 0.0
    fill_color: 0 # 0
    border: [-400, -720]
    clip_box: *clip_box

augment_hsv: &augment_hsv
  type: augment_hsv
  kwargs:
    hgain: 0.015
    sgain: 0.7
    vgain: 0.4
    color_mode: "BGR"

mixup: &mixup
  type: yolox_mixup_cv2
  kwargs:
    extra_input: True
    input_size: *tar_size
    mixup_scale: [0.8, 1.6]
    fill_color: 0
    clip_box: *clip_box

flip: &flip
  type: flip
  kwargs:
    flip_p: 0.5

to_tensor: &to_tensor
  type: custom_to_tensor

train_resize: &train_resize
  type: keep_ar_resize_max
  kwargs:
    #max_size: 640
    #padding_type: left_top
    #padding_val: 0
    random_size: [18, 32]

test_resize: &test_resize
  type: keep_ar_resize_max
  kwargs:
    max_size: 1440
    # padding_type: left_top
    # padding_val: 0

dataset:
  train:
    dataset:
      type: mot
      kwargs:
        num_classes: *num_classes
        num_ids: *num_ids
        ignore_vis_under: 0.05
        multiframerates: [1, 2, 4, 8, 16, 25, 36, 50, 75]
        frame_involved: 6
        num_expected: 1
        meta_file:
          - /mnt/lustre/share/fengweitao/crowd_human/annotations/train.json
          - /mnt/lustre/share/fengweitao/crowd_human/annotations/val.json
          - /mnt/cache/fengweitao/custom_lists/cityscapes_train.json.id.json
          - /mnt/cache/fengweitao/custom_lists/cityscapes_val.json.id.json
          - /mnt/cache/fengweitao/custom_lists/ETHZ.json.id.json
          - /mnt/lustre/fengweitao/share/HIE20/videos/annotations/train.json
          - /mnt/lustre/share/fengweitao/MOT17/annotations/train.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir:
              - /
              - /
              - /
              - /
              - /
              - /
              - /
            color_mode: BGR
        transformer:
          [
            *mosaic,
            *random_perspective,
            *mixup,
            *augment_hsv,
            *flip,
            *train_resize,
            *to_tensor,
          ]
        noaug_ratio: 0.8
        transformer_noaug:
          &transform_noaug [*augment_hsv, *flip, *train_resize, *to_tensor]
        cache:
          cache_dir: ./caches2
          cache_name: mot17_mix_train.pkl
        extra_cache: [/mnt/lustre/fengweitao/code/EOD/caches2/hie.pkl]
        clip_box: *clip_box
    batch_sampler:
      type: base
      kwargs:
        sampler:
          type: dist
          kwargs: {}
        batch_size: 4
  test:
    dataset:
      type: mot
      kwargs:
        num_classes: *num_classes
        frame_involved: 1
        num_expected: 1
        meta_file: &gt_file /mnt/lustre/share/fengweitao/MOT17/annotations/train_multi_framerate_brief_sep_val.json
        image_reader:
          type: fs_opencv
          kwargs:
            image_dir: /
            color_mode: BGR
        transformer: [*test_resize, *to_tensor]
        evaluator:
          type: TrackEval
          kwargs:
            gt_file: *gt_file
            iou_thresh: 0.5
            fppi: [0.5, 1.0, 1.5, 2.0, 3.0, 4.0]
            num_classes: *num_classes
            track_eval:
              METRICS: ["HOTA", "CLEAR"]
              THRESHOLD: 0.5
              BENCHMARK: MOT17
              USE_PARALLEL: true
              NUM_PARALLEL_CORES: 8
            group_by: ["S-1-", "S-16-", "S-50-"]
            formatter: "{root}/{seq}/{fr}.{ext}"
        #evaluator:
        #  type: MR
        #  kwargs:
        #    gt_file: *gt_file
        #    iou_thresh: 0.5
        #    fppi: [0.5, 1.0, 1.5, 2.0, 3.0, 4.0]
        #    num_classes: *num_classes
        clip_box: *clip_box
        cache:
          cache_dir: ./caches2
          cache_name: mot17_mix_train.pkl
    batch_sampler:
      type: sequence
      kwargs:
        sampler:
          type: dist_seq
          kwargs: {}
        batch_size: 1
  dataloader:
    type: mot
    kwargs:
      num_workers: 12
      alignment: 32
      worker_init: True
      pad_type: batch_pad
  builder_type: custom

trainer: # Required.
  max_epoch: &max_epoch 90 # total epochs for the training
  save_freq: 5
  test_freq: 10
  only_save_latest: True
  optimizer: # optimizer = SGD(params,lr=0.01,momentum=0.937,weight_decay=0.0005)
    register_type: yolov5
    type: SGD
    kwargs:
      lr: 0.00001
      momentum: 0.9
      nesterov: True
      weight_decay: 0.0005
  lr_scheduler:
    lr_register_type: yolox_base
    warmup_epochs: 2 # set to be 0 to disable warmup. When warmup,  target_lr = init_lr * total_batch_size
    warmup_type: yolox_cos
    type: YoloXCosineLR
    kwargs:
      T_max: *max_epoch
      min_lr_scale: 0.05
      no_aug_epoch: &no_aug_epoch 10

saver:
  save_dir: checkpoints/base_x_m17_base_hie_assoc
  pretrain_model: pretrained/coco.mot.pth
  results_dir: results_dir/base_x_m17_base_hie_assoc
  auto_resume: True
  save_result: True

hooks:
  - type: custom_auto_save
    kwargs:
      save_epochs: [50, 60]
  - type: train_val_logger
    kwargs:
      freq: 10
      skip_first_k: 5
      logdir: log/base_x_m17_base_hie_assoc
  - type: yolox_mot_noaug
    kwargs:
      no_aug_epoch: *no_aug_epoch
      max_epoch: *max_epoch
      transformer: *transform_noaug
      test_freq: 5
  - type: auto_save_best

ema:
  enable: True
  ema_type: exp
  kwargs:
    decay: 0.9998

Bn: &Bn
  type: solo_bn
  # kwargs:
  #    bn_group_size: 2

net:
  - name: backbone
    type: mot_wrapper
    kwargs:
      cfg:
        type: yolox_x
        kwargs:
          out_layers: [2, 3, 4]
          out_strides: [8, 16, 32]
          normalize: *Bn
          act_fn: { "type": "Silu" }
  - name: neck
    prev: backbone
    type: mot_wrapper
    kwargs:
      cfg:
        type: YoloxPAFPN
        kwargs:
          depth: &depth 1.33
          out_strides: [8, 16, 32]
          act_fn: { "type": "Silu" }
          normalize: *Bn
  - name: roi_head
    prev: neck
    type: mot_wrapper
    kwargs:
      cfg:
        type: YoloXHeadwID
        kwargs:
          num_classes: *num_classes # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
          num_ids: *num_ids
          # normalize_id: True
          fuse_lvls_for_id: True
          width: 1.25
          num_point: &dense_points 1
          act_fn: { "type": "Silu" }
          normalize: *Bn
  - name: assoc_head
    prev: roi_head
    type: yolox_assoc
    kwargs:
      feature_type: low
      auto_framerate: True
      control: sim
      num_classes: *num_classes
      pre_nms_score_thresh: 0.001
      nms:
        type: naive
        nms_iou_thresh: 0.7
      anchor_generator:
        type: fcos # yolox
        kwargs:
          dense_points: *dense_points
          center: False 
  - name: yolox_post
    prev: roi_head
    type: yolox_post_w_assoc
    kwargs:
      num_classes: *num_classes # number of classes including backgroudn. for rpn, it's 2; for RetinaNet, it's 81
      num_ids: *num_ids
      balanced_loss_weight: auto
      balance_scale: 2
      dismiss_aug: True
      ignore_aug: True
      cfg:
        loc_loss:
          type: iou_loss
          kwargs:
            loss_type: square_iou
            loss_weight: 5.0
        cls_loss:
          type: sigmoid_cross_entropy
        obj_loss:
          type: sigmoid_cross_entropy
        id_loss:
          type: sigmoid_cross_entropy
        assoc_loss:
          type: sigmoid_cross_entropy
        anchor_generator:
          type: fcos # yolox
          kwargs:
            dense_points: *dense_points
            center: False
        roi_supervisor:
          type: ota_w_id
          kwargs:
            num_classes: *num_classes
            num_ids: *num_ids
            matcher:
              type: ota_w_id
              kwargs:
                num_classes: *num_classes
        roi_predictor:
          type: yolox_w_id
          kwargs:
            num_classes: *num_classes
            pre_nms_score_thresh: 0.001
            nms:
              type: naive
              nms_iou_thresh: 0.7
